debug: false

logging:
  level:
    ts.instagram: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/instagram
    username: admin
    password: 1q2w3e4r!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql.init.mode: always
mybatis:
  type-aliases-package: ts.instagram.domain
  configuration:
    map-underscore-to-camel-case: true
      #mapper-locations: classpath:mapper/*.xml
